#                ANALYSIS OF AMAZON CELL PHONE REVIEWS

In [1]:
#Importing the libraries
import numpy as np
import pandas as pd

In [2]:
#Importing the dataset
dataset = pd.read_csv(r'C:\Users\Deepika\Documents\20191226-reviews.txt', delimiter = '\t', quoting = 3)

In [3]:
dataset

asin               name  rating                  date  verified  \
0      B0000SX2UC              Janet       3    "October 11, 2005"     False   
1      B0000SX2UC         Luke Wyatt       1     "January 7, 2004"     False   
2      B0000SX2UC             Brooke       5   "December 30, 2003"     False   
3      B0000SX2UC      amy m. teague       3      "March 18, 2004"     False   
4      B0000SX2UC      tristazbimmer       4     "August 28, 2005"     False   
...           ...                ...     ...                   ...       ...   
67981  B081H6STQQ              jande       5     "August 16, 2019"     False   
67982  B081H6STQQ            2cool4u       5  "September 14, 2019"     False   
67983  B081H6STQQ              simon       5       "July 14, 2019"     False   
67984  B081TJFVCJ  Tobiasz Jedrysiak       5   "December 24, 2019"      True   
67985  B0825BB7SG      Owen Gonzalez       5   "December 11, 2019"     False   

                                                   title  \
0                          "Def not best, but not worst"   
1                            Text Messaging Doesn't Work   
2                                        Love This Phone   
3                              "Love the Phone, BUT...!"   
4         "Great phone service and options, lousy case!"   
...                                                  ...   
67981  "Awesome Phone, but finger scanner is a big mi...   
67982                                    Simply Amazing!   
67983  "great phon3, but many bugs need to fix. still...   
67984                                  Phone is like new   
67985                    Outstanding phone for the price   

                                                    body  helpfulVotes  
0      "I had the Samsung A600 for awhile which is ab...           1.0  
1      "Due to a software issue between Nokia and Spr...          17.0  
2      "This is a great, reliable phone. I also purch...           5.0  
3      "I love the phone and all, because I really di...           1.0  
4      "The phone has been great for every purpose it...           1.0  
...                                                  ...           ...  
67981  "I love the camera on this phone. The screen i...           1.0  
67982  "I've been an Xperia user for several years an...           1.0  
67983                         buy one more for my cousin           NaN  
67984  Product looks and works like new. Very much re...           NaN  
67985  I love the size and style of this phone. It is...           NaN  

[67986 rows x 8 columns]

In [4]:
#Checking for null values
dataset.isnull().any()

asin            False
name             True
rating          False
date            False
verified        False
title            True
body             True
helpfulVotes     True
dtype: bool

In [5]:
#Replacing null values
dataset['title'].mode()

0    Five Stars
dtype: object

In [6]:
dataset.fillna(dataset['title'].mode()[0],inplace = True)

In [7]:
#Rechecking for null values
dataset.isnull().any()

asin            False
name            False
rating          False
date            False
verified        False
title           False
body            False
helpfulVotes    False
dtype: bool

In [9]:
#Importing NLP libraries
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Deepika\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [10]:
#Applying NLP
c = []
for i in range(0,67986):
    review = dataset["title"][i]
    review = re.sub('[^a-zA-Z]',' ',review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    c.append(review)

In [11]:
c

['def best worst',
 'text messag work',
 'love phone',
 'love phone',
 'great phone servic option lousi case',
 'work great',
 'wanna cool nokia',
 'problem univers headset',
 'cool phone',
 'piss littl bit',
 'work great dropt',
 'slow annoy fragil heavi bulki',
 'worth pay someth els',
 'great free phone sprint custom',
 'stupid phone',
 'exel servic',
 'love',
 'phone lock',
 'excel product',
 'warn',
 'nextel boost phone',
 'nice',
 'seem work exist sim card',
 'suppli need',
 'five star',
 'job',
 'awesom',
 'one star',
 'cheap ok qualiti',
 'three star',
 'phone gave concuss may come faulti batteri',
 'tough phone',
 'year',
 'simpli great',
 'great',
 'motorola c',
 'good littl phone',
 'great phone',
 'perfect bare bone practic indestruct phone',
 'motorola fan',
 'solid phone',
 'great dispos phone',
 'two one',
 'tough littl phone',
 'boost mobil longer allow iden servic',
 'five star',
 'bought mother mother day',
 'work network',
 'good boost phone',
 'sim card',
 'boost ph

In [12]:
#Importing libraries
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MinMaxScaler

In [13]:
cv = CountVectorizer(max_features = 1500)
ms = MinMaxScaler()

In [14]:
cv

CountVectorizer(max_features=1500)

In [15]:
x = cv.fit_transform(c).toarray()

In [16]:
x.shape

(67986, 1500)

In [17]:
y = dataset.iloc[:,2:3].values

In [18]:
y

array([[3],
       [1],
       [5],
       ...,
       [5],
       [5],
       [5]], dtype=int64)

In [19]:
y = ms.fit_transform(y)

In [20]:
y

array([[0.5],
       [0. ],
       [1. ],
       ...,
       [1. ],
       [1. ],
       [1. ]])

In [21]:
#Spitting data into train and test sets
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20, random_state = 0)

In [23]:
#Importing libraries
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [24]:
#Initialising the model
model = Sequential()

In [25]:
#Adding input layer
model.add(Dense(input_dim = 1500, kernel_initializer = "random_uniform", activation = 'relu', units = 1000))

In [26]:
#Adding hidden layer
model.add(Dense(units = 750, kernel_initializer = "random_uniform", activation = 'relu'))

In [27]:
#Adding output layer
model.add(Dense(units = 1, kernel_initializer = "random_uniform", activation = 'sigmoid'))

In [28]:
#Configuring the learning process
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [29]:
#Training the model
model.fit(x_train, y_train, epochs = 1, batch_size = 500)

Epoch 1/1
54388/54388 [==============================] - 24s 437us/step - loss: 0.4337 - accuracy: 0.6407


In [30]:
y_pred = model.predict(x_test)

In [31]:
y_pred

array([[0.93724644],
       [0.9937681 ],
       [0.25324005],
       ...,
       [0.704205  ],
       [0.43813476],
       [0.9937681 ]], dtype=float32)

In [37]:
y_pred = (y_pred>0.5)

In [38]:
y_pred

array([[ True],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [ True]])

In [32]:
y_test

array([[1.  ],
       [1.  ],
       [0.5 ],
       ...,
       [0.75],
       [0.5 ],
       [1.  ]])

In [33]:
y_test = (y_test>0.5)

In [34]:
y_test

array([[ True],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [ True]])

In [35]:
#Calculating confusion matrix
from sklearn.metrics import confusion_matrix

In [39]:
cm = confusion_matrix(y_test,y_pred)

In [40]:
cm

array([[3050, 1272],
       [ 625, 8651]], dtype=int64)

In [41]:
#Calculating accuracy
from sklearn.metrics import accuracy_score

In [42]:
accuracy = accuracy_score(y_test,y_pred)

In [43]:
accuracy

0.8604941903221062

In [45]:
#Saving the model
model.save('project.h5')

In [53]:
#Saving CountVectorizer
import pickle

In [54]:
pickle.dump(cv, open("vectorizer.pickle","wb"))